"""Initial migration

Revision ID: 944fe64b7f39
Revises: 
Create Date: 2024-02-08 12:55:32.627222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944fe64b7f39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_group')

    # ### end Alembic commands ###
